# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-2022

steps:
- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: "BruDelme"
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      az vm start --resource-group Playground --name myvm
